version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:8.2.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=cartier419
    volumes:
      - es_data:/usr/share/elasticsearch/data
        #ports:
        #- target: 9200
        #published: 9200
    expose:
      - 9200
    networks:
      - elastic
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.elastic.entrypoints=websecure"
      - "traefik.http.routers.elastic.rule=Host(`elastic.carti3r.tk`)"
      - "traefik.http.services.elastic.loadbalancer.server.port=9200"
  kibana:
    image: kibana:8.2.2
    environment:
      - ELASTICSEARCH_URL=http://0.0.0.0:9200/ 
      - ELASTICSEARCH_USERNAME=alg_kibana
      - ELASTICSEARCH_PASSWORD=cartier419
        #ports:
        #- target: 5601
        #published: 5601
    expose:
      - 5601
    depends_on:
      - elasticsearch
    networks:
      - elastic      
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.kibana.entrypoints=websecure"
      - "traefik.http.routers.kibana.rule=Host(`kibana.carti3r.tk`)"
      - "traefik.http.services.kibana.loadbalancer.server.port=5601"
volumes:
  es_data:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge
  proxy:
      external: true
